apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreservation
  labels:
    app: myreservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreservation
  template:
    metadata:
      labels:
        app: myreservation
    spec:
      containers:
        - name: myreservation
          image: user1919.azurecr.io/myreservation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m