apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyReservation
  labels:
    app: MyReservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyReservation
  template:
    metadata:
      labels:
        app: MyReservation
    spec:
      containers:
        - name: MyReservation
          image: username/MyReservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5